language: php

php:
  - '7.2'
  - '7.3'

env:
  - SYMFONY_REQUIRE="3.4.*"
  - SYMFONY_REQUIRE="4.4.*"
  - SYMFONY_REQUIRE="5.0.*"
  - SYMFONY_REQUIRE="5.1.*"

install:
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex
  - rm -rf vendor/* composer.lock
  - composer install --prefer-dist --no-progress

script: make test
