language: php

php:
    - '7.2'
    - '7.3'
    - '7.4'

env:
    - SYMFONY_REQUIRE="4.4.*"
    - SYMFONY_REQUIRE="5.3.*"

matrix:
    include:
        - php: 7.2
          env:
            - CS_FIXER=1
        
        - php: 8.0
          env:
            - SYMFONY_REQUIRE="6.0.*"
            - STABILITY=dev

install:
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex
    - rm -rf composer.lock vendor/*
    - if [[ ${STABILITY} ]]; then composer config minimum-stability ${STABILITY}; fi;
    - composer install --prefer-dist --no-progress

script:
    - if [[ ${CS_FIXER} == "1" ]]; then make php_cs_fixer_check; fi
    - make test
