services:
  dama_menu.twig.menu_extension:
    class: DAMA\MenuBundle\Twig\MenuExtension
    arguments: ["@service_container"]
    tags:
      - { name: twig.extension }

  dama_menu.node_factory:
    class: DAMA\MenuBundle\Node\NodeFactory

  dama_menu.menu_factory:
    class: DAMA\MenuBundle\Menu\MenuFactory
    arguments: ["@dama_menu.menu_config_provider", "@dama_menu.menu_tree_traverser"]
    public: true

  dama_menu.menu_config_provider:
    class: DAMA\MenuBundle\MenuConfig\MenuConfigProvider
    public: true

  dama_menu.menu_tree_traverser:
    class: DAMA\MenuBundle\MenuTree\MenuTreeTraverser

  dama_menu.node_visitor.filter:
    class: DAMA\MenuBundle\NodeVisitor\NodeFilter
    arguments: ["@security.token_storage", "@security.authorization_checker"]
    tags:
      - { name: dama_menu.node_visitor, priority: 1 }

  dama_menu.node_visitor.activator:
    class: DAMA\MenuBundle\NodeVisitor\NodeActivator
    arguments: ["@request_stack"]
    tags:
      - { name: dama_menu.node_visitor, priority: 2 }

  dama_menu.node_visitor.node_route_propagator:
      class: DAMA\MenuBundle\NodeVisitor\NodeRoutePropagator
      tags:
        - { name: dama_menu.node_visitor, priority: 3 }
