name: Build

on: [pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Test
        strategy:
            fail-fast: false
            matrix:
                include:
                -   php: 7.2
                    composer-flags: --prefer-lowest
                -   php: 7.3
                -   php: 7.4
                    SYMFONY_REQUIRE: 5.4.*
                -   php: 8.0
                -   php: 8.1
                    SYMFONY_REQUIRE: 6.0.*
                -   php: 8.1
                    stability: dev
                    SYMFONY_REQUIRE: 6.1.*

        steps:
        -   uses: actions/checkout@v2
        
        -   name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: "${{ matrix.php }}"
                coverage: none

        -   name: Configure Composer minimum stability
            if: matrix.stability
            run: composer config minimum-stability ${{ matrix.stability }}
        
        -   name: Install symfony/flex
            run: composer global require symfony/flex

        -   name: Install dependencies
            env:
                SYMFONY_REQUIRE: "${{ matrix.SYMFONY_REQUIRE }}"
            run: composer update ${{ matrix.composer-flags }} --prefer-dist
        
        -   name: Phpunit
            run: make test
            
    cs-fixer:
        runs-on: ubuntu-latest
        name: CS-Fixer

        steps:
        -   uses: actions/checkout@v2

        -   name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: "7.4"

        -   name: Install dependencies
            run: composer update --prefer-dist

        -   name: PHP CS Fixer
            run: make php_cs_fixer_check
    
    php-stan:
        runs-on: ubuntu-latest
        name: PHPStan
    
        steps:
        -   uses: actions/checkout@v2
    
        -   name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: "8.0"
    
        -   name: Install dependencies
            run: composer update --prefer-dist
    
        -   name: PHPStan
            run: make phpstan
